# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topn', models.IntegerField(default=20)),
                ('DictSize', models.IntegerField(default=10)),
                ('data', models.FileField(upload_to='uploads/')),
                ('ppm', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PLSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(default=5)),
                ('topn', models.IntegerField(default=20)),
                ('DictSize', models.IntegerField(default=10)),
                ('data', models.FileField(upload_to='uploads/')),
                ('ppm', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
